import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://erpqa.azurewebsites.net/auth/login');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('sara');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('password@123');
  await page.getByRole('textbox', { name: 'Enter the CAPTCHA' }).click();
  await page.getByRole('textbox', { name: 'Enter the CAPTCHA' }).fill('123456');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Estimation' }).click();
  await page.goto('https://erpqa.azurewebsites.net/estimation');
  await page.getByRole('textbox', { name: 'Enter Weight Barcode Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Weight Barcode Number' }).fill('20');
  await page.getByRole('textbox', { name: 'Enter Weight Barcode Number' }).press('Enter');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: 'Print Estimation' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('switch').first().check();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('textbox', { name: 'Enter Price Per Gram' }).click();
  await page.getByRole('textbox', { name: 'Enter Price Per Gram' }).fill('4500');
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('switch').nth(2).check();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Sara | C-1 | Self |').click();
  await page.getByText('Select Staff').click();
  await page.getByRole('button', { name: 'Save & print' }).click();
  await page.getByRole('button', { name: 'Estimation History' }).click();
  await page.getByText('Est-1').click();
  await page.getByRole('cell', { name: 'Kadaa Silver | Silver' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Estimation TypeAll').click();
  await page.getByText('Barcode-Weight').click();
  await page.getByRole('button', { name: 'Open calendar' }).click();
  await page.getByRole('button', { name: '01/05/' }).click();
  await page.getByRole('button', { name: '02/05/' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
});